# Generated by Django 5.1.7 on 2025-03-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPitDog', '0002_tipoproduto_cardapio_produtos_typeprodutc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='ingredients',
            field=models.ManyToManyField(to='AppPitDog.produtos'),
        ),
    ]
