# Generated by Django 5.1.7 on 2025-03-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPitDog', '0003_remove_cardapio_ingredients_cardapio_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
