# Generated by Django 5.1.7 on 2025-03-31 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPitDog', '0004_cardapio_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em produção', 'Em produção'), ('Preparado', 'Preparado')], default='Aguardando', max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cardapio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPitDog.cardapio')),
            ],
        ),
    ]
