# Generated by Django 5.1.7 on 2025-03-31 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPitDog', '0005_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cardapio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPitDog.cardapio')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
