# Generated by Django 5.1.7 on 2025-03-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPitDog', '0006_carrinho_delete_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='cardapio_item',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cardapio_item',
            field=models.ManyToManyField(to='AppPitDog.cardapio'),
        ),
    ]
