# Generated by Django 5.1.7 on 2025-03-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPitDog', '0009_rename_data_pedido_carrinho_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='carrinho',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='cardapio_item',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='cardapio_item',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='itens',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='ItemCarrinho',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
