# Generated by Django 5.1.7 on 2025-03-31 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPitDog', '0011_carrinho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
