# Generated by Django 5.1.7 on 2025-03-31 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPitDog', '0012_delete_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPitDog.tipoproduto'),
        ),
    ]
