# Generated by Django 5.1.7 on 2025-03-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPitDog', '0013_cardapio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='TypeProdutc',
        ),
    ]
